import React, { Component } from 'react'
import '../css/About.css'

export class About extends Component {
    render() {
        return (
            <div class="col-lg-8 col-md-8 main">
                <div class="content_bottom_left">
                    <div class="single_page_area">
                        <h2 class="post_titile">About us </h2>
                        <div class="single_page_content">
                            <p className='p2'>Nunc tincidunt, elit non cursus euismod, lacus augue ornare metus, egestas imperdiet nulla nisl quis mauris. Suspendisse a pharetra urna. Morbi dui lectus, pharetra nec elementum eget, vulputate ut nisi. Aliquam accumsan, nulla sed feugiat vehicula, lacus justo semper libero, quis porttitor turpis odio sit amet ligula. Duis dapibus fermentum orci, nec malesuada libero vehicula ut. Integer sodales, urna eget interdum eleifend, nulla nibh laoreet nisl, quis dignissim mauris dolor eget mi. Donec at mauris enim. Duis nisi tellus, adipiscing a convallis quis, tristique vitae risus. Nullam molestie gravida lobortis. Proin ut nibh quis felis auctor ornare. Cras ultricies, nibh at mollis faucibus, justo eros porttitor mi, quis auctor lectus arcu sit amet nunc. Vivamus gravida vehicula arcu, vitae vulputate augue lacinia faucibus.</p>
                            <p className='p2'>Pellentesque placerat pulvinar lectus, ac ultricies quam. Nulla diam felis, dignissim sollicitudin lacus sit amet, convallis porttitor velit. Nunc ultricies turpis eget nisi pretium bibendum. Vestibulum aliquam in magna a porta. Nullam pellentesque maximus mattis. Vestibulum viverra dapibus iaculis. Nullam eleifend scelerisque sem eu auctor. Quisque porta justo id lectus hendrerit, sit amet accumsan ligula hendrerit. Cras mattis consequat nibh, quis tincidunt libero sodales non. Quisque commodo, lacus vel porttitor suscipit, ex lacus ornare sapien, id bibendum urna leo a elit. In ullamcorper suscipit accumsan. Phasellus molestie mi ipsum, at commodo justo interdum sit amet. Vestibulum interdum cursus sagittis. </p>
                            <p className='p2'>Ut imperdiet convallis lobortis.
                                Praesent bibendum tristique tempor. Donec commodo vitae lorem at efficitur. Donec vitae ipsum auctor, mattis turpis nec, vehicula nunc. Aliquam ultrices tincidunt nisl, nec laoreet sapien cursus nec. Vestibulum dapibus cursus quam quis ornare. Proin interdum euismod dui non dapibus. Phasellus pharetra consectetur commodo. Pellentesque et justo in eros volutpat tristique. Donec id est nisl. Ut sit amet rutrum dui. Quisque condimentum turpis sit amet enim interdum, non consequat metus lobortis. Nulla tristique libero vitae dolor vehicula sollicitudin. Sed egestas massa ut diam tincidunt euismod. Donec cursus libero nec risus eleifend, quis rutrum sapien commodo. Suspendisse vestibulum sem ac mollis viverra.</p>
                            <p className='p2'>"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains."</p>
                            <blockquote> Donec volutpat nibh sit amet libero ornare non laoreet arcu luctus. Donec id arcu quis mauris euismod placerat sit amet ut metus. Sed imperdiet fringilla sem eget euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque adipiscing, neque ut pulvinar tincidunt, est sem euismod odio, eu ullamcorper turpis nisl sit amet velit. Nullam vitae nibh odio, non scelerisque nibh. Vestibulum ut est augue, in varius purus. </blockquote>
                            <p className='p2'>Quisque ligulas ipsum, euismod atras vulputate iltricies etri elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla nunc dui, tristique in semper vel, congue sed ligula. Nam dolor ligula, faucibus id sodales in, auctor fringilla libero. Pellentesque pellentesque tempor tellus eget hendrerit. Morbi id aliquam ligula. Aliquam id dui sem. Proin rhoncus consequat nisl, eu ornare mauris tincidunt vitae. Vestibulum sodales ante a purus volutpat euismod. Proin sodales quam nec ante sollicitudin lacinia. Ut egestas bibendum tempor. Morbi non nibh sit amet ligula blandit ullamcorper in nec risus. Pellentesque fringilla diam faucibus tortor bibendum vulputate. Etiam turpis urna, rhoncus et mattis ut, dapibus eu nunc. Nunc sed aliquet nisi. Nullam ut magna non lacus adipiscing volutpat. Aenean odio mauris, consectetur quis consequat quis, blandit a nunc. Sed orci erat, placerat ac interdum ut, suscipit eu augue. Nunc vitae mi tortor. Ut vel justo quis lectus elementum </p>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

export default About